# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 07:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('ship', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='connection',
            name='system_A',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='System_A', to='tracker.System'),
        ),
        migrations.AddField(
            model_name='connection',
            name='system_B',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='System_B', to='tracker.System'),
        ),
        migrations.AddField(
            model_name='character',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.System'),
        ),
    ]
