# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 08:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20160218_0801'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='connection',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='connection',
            name='system_A',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='system_B',
        ),
    ]
