# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 08:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20160218_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='system_A',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='System_A', to='tracker.System'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='connection',
            name='system_B',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='System_B', to='tracker.System'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='connection',
            unique_together=set([('system_A', 'system_B')]),
        ),
        migrations.AlterIndexTogether(
            name='connection',
            index_together=set([('system_A', 'system_B')]),
        ),
    ]
