# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 00:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_auto_20160219_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 20, 0, 52, 8, 605945, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='connection',
            name='verification_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
