# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_auto_20160220_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='lifetime_points',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='character',
            name='points',
            field=models.FloatField(default=0.0),
        ),
    ]
