# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_auto_20160221_0439'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='sysid',
            field=models.CharField(default='0', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
