# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_system_sysid'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='color_code',
            field=models.CharField(default='k10', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
