# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_auto_20160221_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='can_timeout',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
